export default [
  {
    bg: '#333333',
    color: '#3F5B98',
    category: 'Healthcare',
    subCategories: ['Skincare', 'Personal care', 'Health', 'Eye care'],
  },
  {
    bg: '#282828',
    color: '#FCBE4A',
    category: 'Food & Drink',
    subCategories: [
      'Fruits & Vegetables',
      'Frozen Food',
      'Bakery',
      'Snacks & Desserts',
      'Beverages',
      'Alcoholic beverages',
      'Noodles & Pasta',
      'Rice & Cooking oil',
    ],
  },
  {
    bg: '#333333',
    color: '#FD5963',
    category: 'Beauty',
    subCategories: ['Skincare', 'Makeup', 'Nail care', 'Perfume'],
  },
  {
    bg: '#282828',
    color: '#FECBCD',
    category: 'Baby & Kids',
    subCategories: [
      'Toys',
      'Trolleys',
      'LEGO®',
      'Electronics',
      'Puzzles',
      'Costumes',
      'Food',
      'Hygiene & Care',
      "Child's room",
      'Feeding accessories',
    ],
  },
  {
    bg: '#333333',
    color: '#F5F5EB',
    category: 'Homeware',
    subCategories: [
      'Air purifiers',
      'Stoves, hoods & ovens',
      'Refrigerators',
      'Coffee & Tea',
      'Air conditioning',
      'Grilling',
      'Vacuum cleaners',
    ],
  },
];
